#????? ???? ?? ??? ??? ? ??? ?? ??? ???? ??..
#spring-boot-starter-data-jpa ???? ????, DB?? ???? ?? ??? ??? ???.!
#Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
#2021-11-19 23:23:36.089 ERROR 52812 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   :
#### ???? ####
#????
#spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#?? build.gradle h2 scop? ???? ?? compileOnly? ????.  ? ?? ???..
# spring-boot-starter-data-jpa ???? ???? ???? DB ?? ???? ??? ??? ??? ??.!

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
